version: "3"

services:
  hansel:
    container_name: hansel   # bitcoin core node
    hostname: hansel
    image: massmux/bitcoincore:v0.21.0
    environment:
      - BX_CONFIG=/opt/nodeworkdir/bx.cfg
    volumes:
      - ./hansel:/root/.bitcoin
      - ./nodeworkdir:/opt/nodeworkdir
    entrypoint: /root/run.sh
    working_dir: /opt/nodeworkdir
    ports:
      - 18443:18443
      - 18444:18444
  gretel:
    container_name: gretel   # bitcoin core node
    hostname: gretel
    image: massmux/bitcoincore:v0.21.0
    environment:
      - BX_CONFIG=/opt/nodeworkdir/bx.cfg
    volumes:
      - ./gretel:/root/.bitcoin
      - ./nodeworkdir:/opt/nodeworkdir
    entrypoint: /root/run.sh
    working_dir: /opt/nodeworkdir
    links:
      - hansel
    ports:
      - 28444:18444
  oz:
    container_name: oz
    hostname: oz
    image: massmux/bitcoincore:v0.21.0
    volumes:
      - ./oz:/opt/emerald-city
    entrypoint: ["/opt/emerald-city/entrypoint.sh"]
    working_dir: /opt/emerald-city
    links:
      - bitcoinjs-regtest-server
      - gretel
  explorer:
    container_name: explorer
    hostname: explorer
    image: blockstream/esplora
    environment:
      - DISABLE_TOR=1 # blockchain-exporer/runs.sh#L37-L45
      - DISABLE_GENERATETOADDRESS=1 # blockchain-exporer/runs.sh#L256-L263
    ports:
      - 50001:50001   # port for connecting electrum, outside connection allowed
      - 8094:80  # port for block explorer, outside connection allowed
    volumes:
      - ./explorer:/data
      - ./explorer/run.sh:/srv/explorer/run.sh # patch to disable Tor and auto mining of 100 blocks...
    command: ['/srv/explorer/run.sh', 'bitcoin-regtest', 'explorer']
    links:
      - gretel
  bitcoinjs-regtest-server:
    container_name: bitcoinjs-regtest-server
    hostname: bitcoinjs-regtest-server
    image: junderw/bitcoinjs-regtest-server
    # uncomment if you want to connect
    # bitcoinjs-lib from outside
    #ports:
    #  - 8888:8080
    links:
      - hansel
    volumes:
      - ./bitcoinjs-regtest-server/bitcoin-data:/root/.bitcoin
      - ./bitcoinjs-regtest-server/run_bitcoind_service.sh:/root/run_bitcoind_service.sh # patch to disable mining of 432 blocks...
  lightningd:
    container_name: lightningd
    hostname: lightningd
    image: elementsproject/lightningd
    depends_on: [ hansel, gretel ]
    ports:
      - 9735:9735
      - 9737:9737   #spark wallet, outside connection allowed
    volumes:
      - ./lightningd/lightning:/root/.lightning
      - ./lightningd/bitcoin:/root/.bitcoin
      - ./lightningd/entrypoint.sh:/opt/entrypoint.sh
      - ./lightningd/spark-wallet:/root/.spark-wallet
    links:
      - hansel
    entrypoint: /opt/entrypoint.sh
  lnd:
    container_name: lnd
    hostname: lnd
    image: lightninglabs/lnd:v0.12.1-beta
    depends_on: [ hansel, gretel ]
    volumes:
      - ./lnd/lnd-data:/root/.lnd
      - ./lnd/entrypoint.sh:/opt/entrypoint.sh
    entrypoint: ["/opt/entrypoint.sh"]
    environment:
      - NETWORK=regtest
      - CHAIN=bitcoin
      - BACKEND=bitcoind
      - RPCUSER=gretel
      - RPCPASS=1337
      - HOSTNAME=0.0.0.0
      - BACKEND_RPC_HOST=gretel
      - BACKEND_ZMQPUBRAWBLOCK=tcp://gretel:38444
      - BACKEND_ZMQPUBRAWTX=tcp://gretel:48444
    ports:
      - 10009:10009
      - 19735:9735
    links:
      - gretel
      - lightningd
  rtl:
    container_name: rtl
    hostname: rtl
    image: shahanafarooqui/rtl:0.10.2
    ports:
      - 3000:3000
    environment:
      - LND_SERVER_URL=https://lnd:8080
      - RTL_CONFIG_PATH=/root/config/    #pass rtl
    volumes:
      - ./rtl/config:/root/config
      #- ./lnd/lnd-data:/root/gretel
    links:
      - lnd
      - gretel







